### ISSUE TITLE
Why BigInteger ?

### ISSUE THREAD

**Issue by sashank** [secretsharing/secretsharing#1]
Any particular reason why BigInteger is chosen ? It really bloats the size of the shares.

**Comment by rkirkman-mitre** [comment]
The size of the output shares is (logically) only twice long as the input: an x and y coordinate whose bit size is equal to the secret.  However, the default string representation (PartFormats) uses base32 encoding.  For per-byte shares, which are easier to compute, the x coordinate is only one byte but two bytes are required for each y coordinate.

**Comment by rkirkman-mitre** [comment]
Note that, for per-byte secrets, the X coordinate can be re-used for all the per-byte shares.  So the size of a secret share for a secret of N bytes is approximately 2*N however it is represented.

**Comment by esialb** [comment]
presuming question answered
