### ISSUE TITLE
Make cli tool available for download

### ISSUE THREAD

**Issue by jakeswenson** [secretsharing/secretsharing#3]
It'd be nice if the cli build were available to download either from the releases or from maven central

**Comment by rkirkman-mitre** [comment]
I'd be happy to make github releases that include the CLI tool.  Maven central is more for libraries than end-user applications, so I'm hesitant to put the shaded single-jar artifact there, but I can imagine people wanting to integrate the CLI tool's code.  Thoughts?

**Comment by jakeswenson** [comment]
Those are good points. However one point in favor of uploading it to central is that it must be GPG signed just like the rest of your artifacts, so there is an implicit trust anchor.

One thing to note if you thing someone could want to reference the cli as a library (which i could maybe see this being useful as a drop wizard command....) would be to make sure that when you share you give is a classifier and set attach artifacts. this way two versions are pushed: the unshared jar, which doesn't include any dependencies, and the shaded jar which is one uber-jar. 
Here is an example: https://github.com/paradoxical-io/cassandra-loader/blob/master/pom.xml#L269

In the end i'm fine with either approach (GitHub or maven central) as long as there is a url to download it this awesome application from!

Thanks!

**Comment by esialb** [comment]
Alright, version 1.1.2 is released to maven central, with a shaded version of the CLI. Artifacts are also available on the [github v1.1.2 release](https://github.com/secretsharing/secretsharing/releases/tag/v1.1.2)
