### ISSUE TITLE
ArrayIndexOutOfBoundsException when restoring multibyte secret with MSB=1

### ISSUE THREAD

**Issue by sbungartz** [secretsharing/secretsharing#4]
Hi, I noticed an issue with splitting and joining secrets where the most significant bit is set.
This can be reproduced with the following simple example:

```java
byte[] secret = new byte[1];
Part[] parts;

// Most significant bit unset => new BigInteger(secret) is positive
secret[0] = (byte) 0x70; // Most significant bit not set
parts = Secrets.split(secret, 2, 2, rng);
Secrets.join(parts); // Does not throw exception (and returns correct result)

// Most significant bit set => new BigInteger(secret) is negative
secret[0] = (byte) 0x80;
parts = Secrets.split(secret, 2, 2, rng);
byte[] restored = Secrets.join(parts); // Throws ArrayIndexOutOfBoundsException
```
The full exception stack trace is 
```
java.lang.ArrayIndexOutOfBoundsException
    at java.lang.System.arraycopy(Native Method)
    at org.mitre.secretsharing.Secrets.joinMultibyte(Secrets.java:175)
    at org.mitre.secretsharing.Part.join(Part.java:286)
    at org.mitre.secretsharing.Secrets.join(Secrets.java:136)
```
This of course does never happen, when generating a new secret using `new BigInteger(192, rng).toByteArray()` which only generates positive numbers.
But since the interface accepts arbitrary byte arrays this seems to be a bug.

**Comment by esialb** [comment]
Thanks for reporting this, I'll fix it and make a new release shortly

**Comment by esialb** [comment]
Version 1.1.3 has been released and should hit maven central shortly.
