### ISSUE TITLE
Website homepage broken

### ISSUE THREAD

**Issue by jonathancross** [secretsharing/secretsharing#5]
**secretsharing.org** loads two html files in iframes, both of which are missing:
* http://secretsharing.org/split.html
* http://secretsharing.org/join.html

**Comment by esialb** [comment]
I'll take a look at this

**Comment by esialb** [comment]
alright it's back

**Comment by jonathancross** [comment]
Thanks!

Any plans to post this code here on GitHub?
Having the code here would allow others to make improvements in a structured way.
Also being that the website is not using https, it would give us _some_ (limited) confidence that we are using what you created. PGP signing would be even better of course.
