### ISSUE TITLE
Reword  "mail to opensource@mitre.org" request in license

### ISSUE THREAD

**Issue by neuhalje** [secretsharing/secretsharing#6]
Thank you for this library!   I'd like to include secret sharing in projects but the "extended APL" used here makes this very, very difficult. 

My request is to reword 

> This project contains content developed by The MITRE Corporation. If this code is used in a deployment or embedded within another project, it is requested that you send an email to opensource@mitre.org in order to let us know where this software is being used.

As

> This project contains content developed by The MITRE Corporation. If this code is used in a deployment or embedded within another project, it is requested **- but not mandatory -**, that you send an email to opensource@mitre.org in order to let us know where this software is being used. **This statement is explicitly not part of the license.**

The issues I see with the original text are

- If I include this lib in an open source project, I have not way of knowing where it is deployed. I do not know if your license allows me to push  this burden of notification to "my softwares users", and who would breach the license, if they do not notify you.  

- Many organisations use license managing software. APL2 is widely accepted as OSS license. APL2 "+ something" would either be rejected OR not recognised as "something special", thus involuntarily making the user break the license.

Things get worse if the code is included in a library and pulled into projects as transitive dependency.

**Comment by rkirkman-mitre** [comment]
I am consulting with MITRE on this request and will provide updates as they are available.

**Comment by neuhalje** [comment]
Hi, any news on that?

**Comment by neuhalje** [comment]
Monthly ping :-)

**Comment by esialb** [comment]
I no longer work for MITRE, so I can't ping legal anymore.  I'm not sure what the state of the project is.

**Comment by neuhalje** [comment]
Thank you for the update
